mindmap
 root((Courses))
    JavaScript  
        Long history
        Popularisation
        British popular 
    TypeScript
     On effectivness<br/>and features
     On Automatic creation
     Uses
          Creative techniques
          Strategic planning
          Argument mapping
    Rust
       Pen and paper
       Mermaid